### ISSUE TITLE
Documentation Epic

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce#381]
### Tasks
- [x] ~~Adding ASP.NET Core identity tables~~ not worth documenting - replaced with prebuilt setup in the template
- [x] Restrictions: Document how to cache per-request state on instances
- [x] Working with dates (c-display, date-fns, differences between DateTime/DateTimeOffset/DateOnly/TimeOnly, client-side default time zone for date displaying). New folks aren't aware that date-fns is available and resort to janky use of the builtin methods on Date, most of which are bad.
- [x] Strategies for authentication + authorization (replaced with template options)
- [x] Explain how the vite integration works
- [x] injecting data from the server (e.g. configuration) into index.html
- [x] Soft deletes
- [ ] More complete examples for bulk saves
- [x] Overriding admin page routes with custom pages
- [x] Restricting routes by role
- [x] Rename "External Types" to "Plain Models", "Unmapped Model", or some other name that makes a little more sense and doesn't give the impression of "external integration" (goes a bit beyond just docs changes, although we don't strictly have to update code references).
- [x] https://github.com/IntelliTect/Coalesce/issues/426
- [x] https://github.com/IntelliTect/Coalesce/issues/100

**Comment by ascott18** [comment]
Document that Restriction instances are cached per operation so you can cache per-request state on their instances (unless you do something weird with DI like register a restriction as a singleton...)
