### ISSUE TITLE
Template additional enhancements

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce#428]
### Tasks
- [x] template: Unit Tests
- [ ] template: Integration Tests
- [x] template: Azure Pipelines starter pipeline
- [x] https://github.com/IntelliTect/Coalesce/issues/440
- [x] https://github.com/IntelliTect/Coalesce/issues/441
- [x] template: Local accounts (first-party username/password)
- [x] template: Other OAuth/OIDC provider
